spring:
  application:
    name: casino-platform

  datasource:
    url: jdbc:postgresql://localhost:5432/casino_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

jwt:
  secret: your-secret-key-change-this-in-production-min-256-bits
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days

cors:
  allowed-origins: http://localhost:3000,http://localhost:3001,http://localhost:3002,http://localhost:3003,http://localhost:8081,http://localhost:8888
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.SQL: DEBUG
